Version Solving Error Fix
mhmzdev/awesome_snackbar_content pull request #18
Opened 2023-03-19 13:03 UTC by JohnF17

## Fix for the version solving error

### Error
`Because every version of awesome_snackbar_content depends on flutter_svg ^1.0.3 and [app] depends on flutter_svg ^2.0.0+1, awesome_snackbar_content is forbidden.`

### Changes made
- Upgraded flutter_svg package to its latest
- Also gave the deprecated color (of flutter_svg) property another solution

2023-04-07 13:29 UTC, jonmountjoy commented
When I use your version, @JohnF17 , I see this in the error logs:

```
flutter: Unable to load asset: "packages/awesome_snackbar_content/assets/bubbles.svg".
flutter: The asset does not exist or has empty data.
flutter: #0   PlatformAssetBundle.load.<anonymous closure>
asset_bundle.dart:254
```

```
flutter: Unable to load asset: "packages/awesome_snackbar_content/assets/types/failure.svg".
```
etc.

2023-04-07 13:43 UTC, jonmountjoy commented
My bad - I needed to recompile.  All is good.  Thank you.

2023-04-08 03:09 UTC, JohnF17 commented
> My bad - I needed to recompile.

Nonetheless, thank you @jonmountjoy, for pointing out what had seemed to be a potential issue and gave a viable solution to those who might encounter it.

> All is good. Thank you.

You are most welcome.

2023-04-15 06:28 UTC, mhmzdev requested changes
Just remove the commented code, I'll review it on my end and will merge
Thanks for putting it here man!

2023-04-15 06:28 UTC, mhmzdev commented on lib/src/awesome_snackbar_content.dart
> +      // else {
remove commented code please

2023-04-15 06:50 UTC, merged

2023-04-15 06:51 UTC, JohnF17 commented on lib/src/awesome_snackbar_content.dart
> +      // else {
I shall do that right about now

2023-04-15 06:55 UTC, JohnF17 commented on lib/src/awesome_snackbar_content.dart
> +      // else {
@mhmzdev, Also should I update the version from the pubspec?

2023-04-15 14:46 UTC, JohnF17 commented on lib/src/awesome_snackbar_content.dart
> +      // else {
This has been resolved i presume