Proposed change to close button
mhmzdev/awesome_snackbar_content pull request #26
Opened 2023-10-18 10:45 UTC by wilsonanyonga

I have changed the close button and removed the inkwell in favour of IconButton widget. this widget is more responsive on mobile compared to the inkwell button. I have also reduced the space between the top and the title row.

2023-11-26 17:37 UTC, mhmzdev commented
@wilsonanyonga can you share the SS please?
Plus, if you have replaced the icon-button just to be focused on mobile this package is being used on web as well by a lot of people so won't it be causing any trouble there?

2023-11-26 18:36 UTC, wilsonanyonga commented
@mhmzdev the change works well on the web as well. it just increases the clickable area.

![WhatsApp Image 2023-11-26 at 21 33 16](https://github.com/mhmzdev/awesome_snackbar_content/assets/13314437/96e67a76-f64e-4291-a932-4c53a264f3a5)

2024-05-16 14:17 UTC, wilsonanyonga reviewed
Those are the suggested changes

2024-09-06 06:23 UTC, mhmzdev requested changes

2024-09-06 06:23 UTC, mhmzdev commented on lib/src/awesome_snackbar_content.dart
> +                    // InkWell(
Please remove the commented code from here

2024-09-06 09:06 UTC, mhmzdev approved these changes

2024-09-06 09:32 UTC, merged